version: "3.3"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      # MySQL database db will be created and user/password will be
      # granted all priviliges on that database. 
      # We are also setting the default root password for MySQL
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      # We will use a volume to persist the data between starts and stops
      # of the containers. 
      - db_vol:/var/lib/mysql
    networks:
      - backend


  api:
    image: node:11
    volumes:
      - ./src:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    depends_on:
      - db
    command: bash -c "npm install && npm run dev"
    ports: 
      - 3000:3000
    networks:
      - backend

# we are using a network to connect these 
# two containers. They will be part of the same virtual network
# called 'backend'. 
networks: 
  backend:

volumes:
  db_vol: 


version: "3.3"
services:
  # frontend:
  #   build: 
  #     dockerfile: Dockerfile.development
  #     context: ./services/frontend
  #   stdin_open: true
  #   tty: true
  #   ports:
  #     - "8002:80"  
  api:
    build: 
      dockerfile: Dockerfile
      context: ./src
    stdin_open: true
    tty: true
    links:
      - mysql
      - mysql:mysql.cloud66.local
      - rabbitmq
      - rabbitmq:rabbitmq.cloud66.local
    environment:
      - RACK_ENV=development
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
    ports:
      - "8000:80"  
  worker:
    build: 
      dockerfile: Dockerfile
      context: ./services/worker
    stdin_open: true
    tty: true
    links:
      - rabbitmq
      - rabbitmq:rabbitmq.cloud66.local
      - api
      - api:api.cloud66.local

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "8080:15672"

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root